version: '3.8'

services:
  fastapi-backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped
    command: >
      sh -c "python -m alembic upgrade head &&
             python -m uvicorn main:app --host 0.0.0.0 --port ${APP_PORT} --reload"

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
